### ISSUE TITLE
Decompiler Doesn't Work Anymore.

### ISSUE THREAD

**Issue by TheGameratorT** [alexey-lysiuk/ListACS#1]
When I decompile new zdoom acs code I get this:

[ERROR.txt](https://github.com/alexey-lysiuk/ListACS/files/2049267/ERROR.txt)

Maybe pcodes are outdated?

**Comment by alexey-lysiuk** [comment]
Yes, unfortunately there are lots of thing not supported yet. Not sure that I will get back to this decompiler in the nearest future.

**Comment by TheGameratorT** [comment]
Are there any chances that you will get back to it?

**Comment by alexey-lysiuk** [comment]
Maybe later, I'm not really interested in its development right now.

**Comment by TheGameratorT** [comment]
Oh okay :)
Also wtfi.exe helps a lot. Thx to that my brother can play :p
