### ISSUE TITLE
Support for StrParam (pcode 352)

### ISSUE THREAD

**Issue by rop-et-belles-oreilles** [alexey-lysiuk/ListACS#3]
The pcode 352 is not supported.
It is mapped to the [StrParam function](https://zdoom.org/wiki/StrParam).

Original Code
```js
SomeString = StrParam(s:SomeString, i:SomeInt);
````

Decompiled to:
```js
UnknownPrint(s:local1, d:local2);
```

**Comment by alexey-lysiuk** [comment]
There are many relatively recent additions to ACS that are not support.
Sorry but at the moment I have no plans to work on the decompiler.

**Comment by rop-et-belles-oreilles** [comment]
@alexey-lysiuk Thanks for the notice.
I'll try to fix the issues I encountered. I was opening the issue just to document the small glitchs I encountered.
Hopefully, I'll be able to do PRs in few weeks.
