### ISSUE TITLE
ListACS used at NorthSec CTF 2019

### ISSUE THREAD

**Issue by h3xstream** [alexey-lysiuk/ListACS#7]
I just wanted to thank you and @jspenguin (original author) for providing this decompiler to the community.
I did a series of reverse engineering challenges which involve understanding the compiled ACS bytecode of a custom map I made. This decompiler made the challenge accessible to more people.

In case, you are curious two write-ups were published describing the challenges : 
 - http://www.agardner.me/securit/ctf/northsec/2019/2019/05/19/northsec-ctf-part-1-doom.html
 - https://re-dojo.github.io/posts/2019-05-26-doom/

**Comment by alexey-lysiuk** [comment]
Actually, I just fixed a few minor issues. Thanks to @jspenguin for creation of ListACS.
